apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finalproject-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Shahdhussien/shared-library-repo-.git' 
    targetRevision: main
    path: K8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ivolve
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
