apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalproject-deployment
  namespace: ivolve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finalproject
  template:
    metadata:
      labels:
        app: finalproject
    spec:
      containers:
      - name: finalproject
        image: shahd0/myimg:281
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
