apiVersion: v1
kind: Service
metadata:
  name: finalproject-service
  namespace: ivolve
spec:
  type: NodePort
  selector:
    app: finalproject
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30007 
